In [1]:
import numpy as np
import tensorflow as tf
from keras.datasets import cifar10
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

Using TensorFlow backend.


In [2]:
# The data, split between train and test sets:
(_, _), (X, y) = cifar10.load_data()
print(X.shape)
print(y.shape)

(10000, 32, 32, 3)
(10000, 1)


In [3]:
encoder = tf.keras.models.load_model('./encoder.h5')

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## Baseline

In [5]:
# clf = LogisticRegression(random_state=0, solver='lbfgs', multi_class='auto').fit(np.reshape(X_train,(X_train.shape[0], -1)), y_train.squeeze())

In [6]:
# clf.score(np.reshape(X_test,(X_test.shape[0], -1)), y_test)

## Self-Supervised pre-training

In [7]:
X_train_repr = encoder(X_train / 255.)
X_test_repr = encoder(X_test / 255.)
print(X_train_repr.shape)
print(X_test_repr.shape)

(8000, 64)
(2000, 64)


In [8]:
clf = LogisticRegression(random_state=0, solver='lbfgs', multi_class='auto').fit(X_train_repr, y_train.squeeze())

In [19]:
clf.score(X_test_repr, y_test.squeeze())
# 0.2205

0.1325

In [10]:
X_train_repr[0]

<tf.Tensor: shape=(64,), dtype=float32, numpy=
array([0.        , 0.02203218, 0.06431255, 0.        , 0.        ,
       0.01628256, 0.00574495, 0.        , 0.00058333, 0.01102319,
       0.        , 0.00774174, 0.        , 0.05404237, 0.01079597,
       0.        , 0.01220455, 0.02269833, 0.        , 0.        ,
       0.02870458, 0.03234017, 0.03352561, 0.        , 0.        ,
       0.        , 0.        , 0.02182167, 0.        , 0.        ,
       0.03413367, 0.        , 0.        , 0.01302883, 0.        ,
       0.02511339, 0.03386034, 0.        , 0.04305923, 0.01520518,
       0.        , 0.        , 0.        , 0.01688802, 0.        ,
       0.00526548, 0.        , 0.03594415, 0.00747574, 0.04394847,
       0.06942847, 0.02991914, 0.        , 0.        , 0.        ,
       0.00039897, 0.        , 0.        , 0.01334965, 0.04753837,
       0.01650756, 0.02549673, 0.        , 0.        ], dtype=float32)>

In [11]:
X_test_repr[0]

<tf.Tensor: shape=(64,), dtype=float32, numpy=
array([0.        , 0.02196622, 0.06120525, 0.        , 0.        ,
       0.01421653, 0.00953932, 0.        , 0.00072643, 0.01154679,
       0.        , 0.00646555, 0.        , 0.05551305, 0.00907742,
       0.        , 0.01302468, 0.01533172, 0.        , 0.        ,
       0.02824804, 0.02621051, 0.02854381, 0.        , 0.        ,
       0.00255286, 0.        , 0.01792722, 0.        , 0.        ,
       0.02563109, 0.        , 0.        , 0.0125089 , 0.        ,
       0.01861791, 0.03106778, 0.        , 0.04388055, 0.01448373,
       0.        , 0.        , 0.        , 0.01143435, 0.        ,
       0.00538129, 0.        , 0.03384916, 0.0037426 , 0.03981137,
       0.0616336 , 0.03772312, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.01178576, 0.04341508,
       0.01345163, 0.02156401, 0.        , 0.        ], dtype=float32)>